/* USER CODE BEGIN Header */
/**
  ******************************************************************************
  * @file           : main.c
  * @brief          : SMS Notification Module using SIM800L + Blue Pill (STM32F103)
  ******************************************************************************
  * @details
  * This firmware implements a blocking SMS alert sender using a SIM800L GSM modem.
  * The Blue Pill controls the modem exclusively via standard AT commands over UART.
  * The module initializes the modem, verifies network registration using AT+CREG?,
  * and sends a predefined hard-coded SMS message to one or more stored phone numbers.
  *
  * Status is indicated using three LEDs connected to GPIOC pins (ACTIVE-HIGH):
  * - PC13: Searching/Network LED
  * - PC14: Sending LED
  * - PC15: Success LED
  *
  * Restrictions:
  * - SMS sending only (no receive/calls/data)
  * - Blocking sequences permitted
  * - Phone numbers and message are compile-time constants
  * - No third-party GSM libraries used
  ******************************************************************************
  * @attention
  * Copyright (c) 2026 STMicroelectronics.
  * All rights reserved.
  ******************************************************************************
  */
/* USER CODE END Header */

/* Includes ------------------------------------------------------------------*/
/**
  * @brief Main HAL and board support header.
  * @details Typically auto-generated by STM32CubeMX. It includes STM32 HAL headers,
  * pin definitions, and peripheral handle declarations (depending on project).
  */
#include "main.h"

/** @brief C standard library: string helper functions (memset, strlen, strstr, strcpy). */
#include <string.h>

/** @brief C standard library: formatted I/O (sprintf). */
#include <stdio.h>

/* Private variables ---------------------------------------------------------*/
/**
  * @brief UART handle for USART1 (used for GSM modem/SIM800L).
  * @details Initialized inside MX_USART1_UART_Init().
  */
UART_HandleTypeDef huart1;

/**
  * @brief UART handle for USART2 (used for debug/log console).
  * @details Initialized inside MX_USART2_UART_Init().
  */
UART_HandleTypeDef huart2;

/* Private function prototypes -----------------------------------------------*/
/**
  * @brief Configure MCU system clock.
  * @details Generated by CubeMX. Sets up oscillator and bus clocks.
  */
void SystemClock_Config(void);

/**
  * @brief Initialize GPIO pins and clocks used by this application.
  * @details Generated by CubeMX. Enables port clocks and configures LED pins.
  */
static void MX_GPIO_Init(void);

/**
  * @brief Initialize USART1 peripheral for GSM modem UART.
  * @details Generated by CubeMX. Sets baud rate, parity, stop bits, etc.
  */
static void MX_USART1_UART_Init(void);

/**
  * @brief Initialize USART2 peripheral for debugging/log UART.
  * @details Generated by CubeMX. Sets baud rate, parity, stop bits, etc.
  */
static void MX_USART2_UART_Init(void);

/**
  * @brief Generic error handler (infinite loop).
  * @details Generated by CubeMX. Used when HAL init/config fails.
  */
void Error_Handler(void);

/* USER CODE BEGIN 0 */

/* ========================================================================== */
/* ============================ Project Definitions ========================== */
/* ========================================================================== */

/**
  * @def GSM_UART_HANDLER
  * @brief UART used to communicate with SIM800L modem.
  * @details
  * This macro allows easy switching of GSM UART if needed.
  * In this project it maps to huart1 (USART1).
  */
#define  GSM_UART_HANDLER huart1

/* ========================================================================== */
/* ============================ LED + GPIO (ASM) ============================= */
/* ========================================================================== */
/**
  * @defgroup LED_GPIO_ASM LED control on GPIOC using inline ASM
  * @brief Low-level LED control functions (set/reset/toggle) via direct register access.
  * @details
  * LEDs are connected to GPIOC pins PC13/PC14/PC15 and are ACTIVE-HIGH:
  * - pin output = 1 => LED ON
  * - pin output = 0 => LED OFF
  * @{
  */

/**
  * @def GPIOC_BASE
  * @brief GPIOC peripheral base address in STM32F103 memory map.
  * @details STM32 peripherals are memory mapped; GPIOC begins at 0x40011000.
  */
#define GPIOC_BASE       (0x40011000UL)

/**
  * @def GPIOC_ODR_ADDR
  * @brief Address of GPIOC Output Data Register (ODR).
  * @details ODR offset is 0x0C from GPIO base.
  */
#define GPIOC_ODR_ADDR   (GPIOC_BASE + 0x0CUL)

/**
  * @def GPIOC_BSRR_ADDR
  * @brief Address of GPIOC Bit Set/Reset Register (BSRR).
  * @details
  * BSRR allows atomic pin operations:
  * - write '1' in bits [0..15]  => SET corresponding pins
  * - write '1' in bits [16..31] => RESET corresponding pins
  * Offset is 0x10 from GPIO base.
  */
#define GPIOC_BSRR_ADDR  (GPIOC_BASE + 0x10UL)

/**
  * @def LED_NETWORK_MASK
  * @brief Bit mask for PC13 (Network/Search LED).
  * @details (1u << 13) means "bit 13 = 1", selecting pin 13.
  */
#define LED_NETWORK_MASK (1u << 13)

/**
  * @def LED_SENDING_MASK
  * @brief Bit mask for PC14 (Sending LED).
  */
#define LED_SENDING_MASK (1u << 14)

/**
  * @def LED_SUCCESS_MASK
  * @brief Bit mask for PC15 (Success LED).
  */
#define LED_SUCCESS_MASK (1u << 15)

/**
  * @brief Set (turn ON) one or more GPIOC pins using BSRR.
  * @details
  * Writing mask to BSRR (lower 16 bits) sets pins to logic 1.
  * This is atomic and does NOT disturb other pin states.
  * @param mask Bitmask of pins to set.
  */
static inline void GPIOC_SetPins_Asm(uint32_t mask)
{
    __asm volatile (
        "ldr r1, =%0   \n"   /* r1 = GPIOC_BSRR address */
        "str %1, [r1]  \n"   /* write mask -> set pins */
        :
        : "i"(GPIOC_BSRR_ADDR), "r"(mask)
        : "r1", "memory"
    );
}

/**
  * @brief Reset (turn OFF) one or more GPIOC pins using BSRR.
  * @details
  * For resetting pins via BSRR, the mask must be shifted left by 16,
  * so it lands in upper half [16..31].
  * This is atomic and does NOT disturb other pin states.
  * @param mask Bitmask of pins to reset.
  */
static inline void GPIOC_ResetPins_Asm(uint32_t mask)
{
    __asm volatile (
        "lsl %1, %1, #16 \n" /* move bits to upper 16 -> reset operation */
        "ldr r1, =%0     \n" /* r1 = GPIOC_BSRR address */
        "str %1, [r1]    \n" /* write -> reset pins */
        :
        : "i"(GPIOC_BSRR_ADDR), "r"(mask)
        : "r1", "memory"
    );
}

/**
  * @brief Toggle one or more GPIOC pins by XOR on ODR register.
  * @details
  * Reads current ODR, XORs with mask, writes back.
  * Used for blinking LED during error state.
  * @warning
  * This is read-modify-write; safe here because code is blocking/single flow
  * and only these LED pins are affected.
  * @param mask Bitmask of pins to toggle.
  */
static inline void GPIOC_TogglePins_ODR_Asm(uint32_t mask)
{
    __asm volatile (
        "ldr r1, =%0     \n" /* r1 = GPIOC_ODR address */
        "ldr r2, [r1]    \n" /* r2 = current ODR value */
        "eor r2, r2, %1  \n" /* toggle selected bits */
        "str r2, [r1]    \n" /* write back */
        :
        : "i"(GPIOC_ODR_ADDR), "r"(mask)
        : "r1", "r2", "memory"
    );
}

/**
  * @name LED helper macros (ACTIVE-HIGH)
  * @brief Convenience wrappers for the LED pins.
  * @{
  */
#define LED_NET_ON()      GPIOC_SetPins_Asm(LED_NETWORK_MASK)   /**< Turn ON Network LED (PC13). */
#define LED_NET_OFF()     GPIOC_ResetPins_Asm(LED_NETWORK_MASK) /**< Turn OFF Network LED (PC13). */

#define LED_SEND_ON()     GPIOC_SetPins_Asm(LED_SENDING_MASK)   /**< Turn ON Sending LED (PC14). */
#define LED_SEND_OFF()    GPIOC_ResetPins_Asm(LED_SENDING_MASK) /**< Turn OFF Sending LED (PC14). */

#define LED_OK_ON()       GPIOC_SetPins_Asm(LED_SUCCESS_MASK)   /**< Turn ON Success LED (PC15). */
#define LED_OK_OFF()      GPIOC_ResetPins_Asm(LED_SUCCESS_MASK) /**< Turn OFF Success LED (PC15). */

#define LED_ALL_OFF()     GPIOC_ResetPins_Asm(LED_NETWORK_MASK | LED_SENDING_MASK | LED_SUCCESS_MASK) /**< Turn OFF all LEDs. */
/** @} */
/** @} */ /* end of LED_GPIO_ASM group */

/* ========================================================================== */
/* ============================ Delay (ASM) ================================= */
/* ========================================================================== */
/**
  * @defgroup DELAY_ASM Busy-wait delays in ASM
  * @brief Simple blocking delays (not timer-based).
  * @{
  */

/**
  * @brief Busy-wait loop (decrement + branch).
  * @param loops Number of iterations to wait.
  */
static inline void Delay_Loops_Asm(volatile uint32_t loops)
{
    __asm volatile (
        "1: subs %0, %0, #1 \n" /* loops = loops - 1 */
        "   bne  1b         \n" /* if not zero, branch to label 1 */
        : "+r"(loops)
        :
        : "cc"
    );
}

/**
  * @brief Approximate millisecond delay using busy-wait loops.
  * @details
  * Calibration factor (2000) is approximate and depends on CPU clock.
  * @param ms Milliseconds to wait (approx).
  */
static inline void Delay_ms_Asm(uint32_t ms)
{
    while(ms--)
    {
        Delay_Loops_Asm(2000);
    }
}
/** @} */ /* end DELAY_ASM */

/* ========================================================================== */
/* ============================ UART2 Logging ================================ */
/* ========================================================================== */
/**
  * @defgroup LOGGING_UART2 Debug logging over USART2
  * @brief Small helper functions to print status messages.
  * @{
  */

/**
  * @brief Print a success message with "[OK]" prefix on USART2.
  * @param msg Null-terminated message string.
  */
void Log_Success(uint8_t *msg)
{
    uint8_t newline[] = "\r\n";
    HAL_UART_Transmit(&huart2, (uint8_t*)"[OK] ", 5, 100);
    HAL_UART_Transmit(&huart2, msg, strlen((char*)msg), 100);
    HAL_UART_Transmit(&huart2, newline, 2, 100);
}

/**
  * @brief Print an error message with "[ERROR]" prefix on USART2.
  * @param msg Null-terminated message string.
  */
void Log_Error(uint8_t *msg)
{
    uint8_t newline[] = "\r\n";
    HAL_UART_Transmit(&huart2, (uint8_t*)"[ERROR] ", 8, 100);
    HAL_UART_Transmit(&huart2, msg, strlen((char*)msg), 100);
    HAL_UART_Transmit(&huart2, newline, 2, 100);
}
/** @} */ /* end LOGGING_UART2 */

/* ========================================================================== */
/* ============================ GSM Constants ================================ */
/* ========================================================================== */
/**
  * @defgroup GSM_CONSTANTS Compile-time constants for SMS
  * @brief Hard-coded phone numbers and message text per project requirements.
  * @{
  */

/**
  * @brief List of destination phone numbers (compile-time constant).
  * @details Requirement: stored numbers must be compile-time constants.
  */
static const char *PHONE_NUMBERS[] =
{
    "09055322375",
    "09200510834",
    "09126043816"
};

/**
  * @brief Number of phone numbers in PHONE_NUMBERS array.
  */
static const uint8_t PHONE_COUNT = (uint8_t)(sizeof(PHONE_NUMBERS) / sizeof(PHONE_NUMBERS[0]));

/**
  * @brief SMS message text (compile-time constant).
  * @details Requirement: message must be hard-coded.
  */
static const uint8_t MESSAGE_TEXT[] = "Alert: System Triggered!";
/** @} */ /* end GSM_CONSTANTS */

/* ========================================================================== */
/* ============================ Robust AT Parsing ============================ */
/* ========================================================================== */
/**
  * @defgroup GSM_AT_PARSER Robust parsing of modem responses
  * @brief Token-based UART response reading for AT commands.
  * @{
  */

/**
  * @enum GSM_WaitResult
  * @brief Possible outcomes while waiting for a modem response token.
  */
typedef enum
{
    GSM_RES_OK = 0,      /**< The "OK" token was detected. */
    GSM_RES_ERROR,       /**< The "ERROR" token was detected. */
    GSM_RES_PROMPT,      /**< The ">" prompt was detected. */
    GSM_RES_TIMEOUT      /**< Timeout expired without expected token. */
} GSM_WaitResult;

/**
  * @brief Read modem output until a token (OK/ERROR/PROMPT) is detected or timeout expires.
  * @details
  * The function reads bytes from GSM UART in small slices (10 ms).
  * It accumulates characters into out_buf if provided.
  * After each received byte, it scans for the provided tokens:
  * - token_prm (e.g., ">") first,
  * - token_err (e.g., "ERROR") second,
  * - token_ok  (e.g., "OK") last.
  *
  * If no token is seen within timeout_ms, returns GSM_RES_TIMEOUT.
  *
  * @param out_buf Optional output buffer for received modem text (can be NULL).
  * @param out_sz Size of out_buf; if buffer exists, it is kept null-terminated.
  * @param token_ok Token string indicating success (can be NULL).
  * @param token_err Token string indicating error (can be NULL).
  * @param token_prm Token string indicating prompt (can be NULL).
  * @param timeout_ms Total timeout window in milliseconds.
  * @return GSM_WaitResult indicating which token ended the wait.
  */
static GSM_WaitResult GSM_ReadUntil(uint8_t *out_buf,
                                   uint16_t out_sz,
                                   const char *token_ok,
                                   const char *token_err,
                                   const char *token_prm,
                                   uint16_t timeout_ms)
{
    uint8_t ch;                         /**< One received byte from UART. */
    uint16_t idx = 0;                   /**< Write index into out_buf. */
    uint32_t start = HAL_GetTick();     /**< Start time for total timeout measurement. */

    if (out_buf != NULL && out_sz > 0)
        out_buf[0] = 0;                 /**< Initialize buffer as empty C-string. */

    while ((HAL_GetTick() - start) < timeout_ms)
    {
        HAL_StatusTypeDef st = HAL_UART_Receive(&GSM_UART_HANDLER, &ch, 1, 10);

        if (st == HAL_OK)
        {
            if (out_buf != NULL && out_sz > 0)
            {
                if (idx < (uint16_t)(out_sz - 1))
                {
                    out_buf[idx++] = ch; /**< Store byte and advance index. */
                    out_buf[idx] = 0;    /**< Keep null-terminated. */
                }
                else
                {
                    out_buf[out_sz - 1] = 0; /**< Prevent overflow; keep string terminated. */
                }
            }

            if (out_buf != NULL)
            {
                if (token_prm && strstr((char*)out_buf, token_prm)) return GSM_RES_PROMPT;
                if (token_err && strstr((char*)out_buf, token_err)) return GSM_RES_ERROR;
                if (token_ok  && strstr((char*)out_buf, token_ok))  return GSM_RES_OK ;
            }
        }
    }

    return GSM_RES_TIMEOUT;
}

/**
  * @brief Send an AT command and wait for "OK" or "ERROR" (robust).
  * @details
  * 1) Transmit the command string over GSM UART.
  * 2) Wait until "OK" or "ERROR" appears in modem output, or timeout occurs.
  *
  * @param cmd AT command string (must include \r\n).
  * @param response Optional response buffer to copy received text into (can be NULL).
  * @param timeout Total timeout in milliseconds.
  * @return 1 if "OK" received, 0 otherwise.
  */
uint8_t GSM_SendCommand(uint8_t *cmd, uint8_t *response, uint16_t timeout)
{
    uint8_t recv_buf[200]; /**< Temporary internal buffer for modem response. */
    memset(recv_buf, 0, sizeof(recv_buf));

    HAL_UART_Transmit(&GSM_UART_HANDLER, cmd, strlen((char*)cmd), 1000);

    GSM_WaitResult res = GSM_ReadUntil(recv_buf, sizeof(recv_buf), "OK", "ERROR", NULL, timeout);

    if (response != NULL)
        strcpy((char*)response, (char*)recv_buf);

    if (res == GSM_RES_OK)
        return 1;

    if (res == GSM_RES_TIMEOUT && response == NULL)
        Log_Error((uint8_t*)"Timeout waiting for modem response");

    return 0;
}

/**
  * @brief Check GSM network registration state via AT+CREG?.
  * @details
  * Sends "AT+CREG?" and waits for "OK".
  * Returns registered if modem reports:
  * - +CREG: 0,1 (registered, home)
  * - +CREG: 0,5 (registered, roaming)
  *
  * @return 1 if registered, 0 otherwise.
  */
uint8_t GSM_CheckNetwork()
{
    uint8_t cmd[] = "AT+CREG?\r\n"; /**< AT command to query registration. */
    uint8_t response[200];         /**< Buffer for modem response text. */
    memset(response, 0, sizeof(response));

    HAL_UART_Transmit(&GSM_UART_HANDLER, cmd, strlen((char*)cmd), 1000);

    GSM_WaitResult res = GSM_ReadUntil(response, sizeof(response), "OK", "ERROR", NULL, 2000);

    if (res != GSM_RES_OK)
        return 0;

    if (strstr((char*)response, "+CREG: 0,1") != NULL || strstr((char*)response, "+CREG: 0,5") != NULL)
        return 1;

    return 0;
}

/**
  * @brief Main GSM flow: init modem, search network, send SMS to all stored numbers.
  * @details
  * LED policy in this function:
  * - At start: Network LED ON (searching)
  * - When sending each SMS: Sending LED ON
  * - On successful send: Success LED ON for 1 second
  * - On any error: all off, then blink Sending LED 5 times
  */
void GSM_SendSMS_Process()
{
    uint8_t cmd_buf[50]; /**< Buffer for formatted AT+CMGS command string. */
    uint8_t ctrlz = 0x1A;/**< Ctrl+Z ASCII (end of SMS text in SIM800L). */

    Log_Success((uint8_t*)"Process Started");

    /* Start in network/searching state */
    LED_ALL_OFF();
    LED_NET_ON();

    if (!GSM_SendCommand((uint8_t*)"ATE0\r\n", NULL, 1000)) {
        Log_Error((uint8_t*)"Failed to disable Echo (ATE0)");
        goto ERROR_STATE;
    }
    Log_Success((uint8_t*)"Echo Disabled (ATE0)");

    if (!GSM_SendCommand((uint8_t*)"AT+CMGF=1\r\n", NULL, 1000)) {
        Log_Error((uint8_t*)"Failed to set Text Mode (CMGF)");
        goto ERROR_STATE;
    }
    Log_Success((uint8_t*)"Text Mode Set (CMGF)");

    uint8_t network_found = 0; /**< Flag that becomes 1 when network registration is confirmed. */
    Log_Success((uint8_t*)"Searching for Network...");

    for (int i = 0; i < 5; i++)
    {
        if (GSM_CheckNetwork())
        {
            network_found = 1;
            break;
        }
        HAL_Delay(2000); /**< Blocking delay between network checks. */
    }

    if (network_found == 0) {
        Log_Error((uint8_t*)"Network registration timeout (CREG)");
        goto ERROR_STATE;
    }
    Log_Success((uint8_t*)"Network Connected Successfully");

    /* Send to all numbers */
    for (uint8_t n = 0; n < PHONE_COUNT; n++)
    {
        LED_NET_OFF();
        LED_OK_OFF();
        LED_SEND_ON();

        Log_Success((uint8_t*)"Sending SMS...");

        sprintf((char*)cmd_buf, "AT+CMGS=\"%s\"\r\n", PHONE_NUMBERS[n]);
        HAL_UART_Transmit(&GSM_UART_HANDLER, cmd_buf, strlen((char*)cmd_buf), 1000);

        uint8_t prompt_resp[120]; /**< Buffer for prompt stage response (waiting for '>'). */
        memset(prompt_resp, 0, sizeof(prompt_resp));

        GSM_WaitResult prm = GSM_ReadUntil(prompt_resp, sizeof(prompt_resp), NULL, "ERROR", ">", 100);

        if (prm != GSM_RES_PROMPT)
        {
            if (prm == GSM_RES_TIMEOUT) Log_Error((uint8_t*)"Timeout waiting for '>' prompt");
            else Log_Error((uint8_t*)"Did not receive '>' prompt from modem");
            goto ERROR_STATE;
        }

        Log_Success((uint8_t*)"Prompt Received, Sending Data...");

        HAL_UART_Transmit(&GSM_UART_HANDLER, (uint8_t*)MESSAGE_TEXT, strlen((char*)MESSAGE_TEXT), 1000);
        HAL_UART_Transmit(&GSM_UART_HANDLER, &ctrlz, 1, 1000);

        uint8_t final_resp[250]; /**< Buffer for final stage response (waiting for OK/ERROR). */
        memset(final_resp, 0, sizeof(final_resp));

        GSM_WaitResult fin = GSM_ReadUntil(final_resp, sizeof(final_resp), "OK", "ERROR", NULL, 5000);

        if (fin == GSM_RES_OK)
        {
            Log_Success((uint8_t*)"SMS Sent Successfully!");
            LED_SEND_OFF();
            LED_OK_ON();
            Delay_ms_Asm(1000);
            LED_OK_OFF();
        }
        else
        {
            if (fin == GSM_RES_TIMEOUT) Log_Error((uint8_t*)"SMS Send Failed (Timeout waiting OK)");
            else Log_Error((uint8_t*)"SMS Send Failed (ERROR received)");
            goto ERROR_STATE;
        }

        Delay_ms_Asm(1000);
    }

    /* back to idle */
    LED_ALL_OFF();
    return;

ERROR_STATE:
    LED_ALL_OFF();
    for (int i = 0; i < 5; i++) {
        GPIOC_TogglePins_ODR_Asm(LED_SENDING_MASK);  /**< Blink sending LED to indicate error. */
        Delay_ms_Asm(100);
    }
}
/** @} */ /* end GSM_AT_PARSER */

/* USER CODE END 0 */

/* ============================== main() ============================== */
/**
  * @brief Application entry point.
  * @details
  * Initializes HAL, clock, GPIO, USARTs and then polls UART2.
  * When user sends 's' or 'S' on UART2, SMS sending process is triggered.
  * @return int (never returns; infinite loop)
  */
int main(void)
{
    uint8_t ch; /**< Single received character from UART2 (debug trigger). */

    HAL_Init();             /**< Initialize HAL library and SysTick. */
    SystemClock_Config();   /**< Configure system clocks. */

    MX_GPIO_Init();         /**< Initialize GPIO (LED pins etc.). */
    MX_USART1_UART_Init();  /**< Initialize USART1 for GSM modem. */
    MX_USART2_UART_Init();  /**< Initialize USART2 for logging/command. */

    Delay_ms_Asm(50);       /**< Small startup delay. */

    while (1)
    {
        if (HAL_UART_Receive(&huart2, &ch, 1, 1) == HAL_OK)
        {
            if (ch == 's' || ch == 'S')
            {
                GSM_SendSMS_Process();
            }
        }

        Delay_ms_Asm(4);
    }
}

/* ============================== Clock ============================== */
/**
  * @brief System Clock Configuration (CubeMX generated).
  * @details
  * Uses HSI as system clock source, no PLL.
  * Configures AHB/APB dividers.
  */
void SystemClock_Config(void)
{
  RCC_OscInitTypeDef RCC_OscInitStruct = {0}; /**< Oscillator configuration structure. */
  RCC_ClkInitTypeDef RCC_ClkInitStruct = {0}; /**< Clock configuration structure. */

  RCC_OscInitStruct.OscillatorType = RCC_OSCILLATORTYPE_HSI; /**< Select HSI oscillator. */
  RCC_OscInitStruct.HSIState = RCC_HSI_ON;                   /**< Turn ON HSI. */
  RCC_OscInitStruct.HSICalibrationValue = RCC_HSICALIBRATION_DEFAULT; /**< Default calibration. */
  RCC_OscInitStruct.PLL.PLLState = RCC_PLL_NONE;             /**< Disable PLL. */
  if (HAL_RCC_OscConfig(&RCC_OscInitStruct) != HAL_OK)
  {
    Error_Handler();
  }

  RCC_ClkInitStruct.ClockType = RCC_CLOCKTYPE_HCLK|RCC_CLOCKTYPE_SYSCLK
                              |RCC_CLOCKTYPE_PCLK1|RCC_CLOCKTYPE_PCLK2; /**< Configure HCLK/SYSCLK/PCLK1/PCLK2. */
  RCC_ClkInitStruct.SYSCLKSource = RCC_SYSCLKSOURCE_HSI; /**< Use HSI as SYSCLK source. */
  RCC_ClkInitStruct.AHBCLKDivider = RCC_SYSCLK_DIV1;     /**< AHB divider = 1. */
  RCC_ClkInitStruct.APB1CLKDivider = RCC_HCLK_DIV1;      /**< APB1 divider = 1. */
  RCC_ClkInitStruct.APB2CLKDivider = RCC_HCLK_DIV1;      /**< APB2 divider = 1. */

  if (HAL_RCC_ClockConfig(&RCC_ClkInitStruct, FLASH_LATENCY_0) != HAL_OK)
  {
    Error_Handler();
  }
}

/* ============================== USART1 ============================== */
/**
  * @brief USART1 Initialization Function (CubeMX generated).
  * @details
  * Configured for SIM800L communication (115200 8N1).
  */
static void MX_USART1_UART_Init(void)
{
  huart1.Instance = USART1;                      /**< Peripheral instance selection. */
  huart1.Init.BaudRate = 115200;                 /**< Baud rate. */
  huart1.Init.WordLength = UART_WORDLENGTH_8B;   /**< 8-bit word length. */
  huart1.Init.StopBits = UART_STOPBITS_1;        /**< 1 stop bit. */
  huart1.Init.Parity = UART_PARITY_NONE;         /**< No parity. */
  huart1.Init.Mode = UART_MODE_TX_RX;            /**< Enable TX and RX. */
  huart1.Init.HwFlowCtl = UART_HWCONTROL_NONE;   /**< No flow control. */
  huart1.Init.OverSampling = UART_OVERSAMPLING_16; /**< Oversampling by 16. */
  if (HAL_UART_Init(&huart1) != HAL_OK)
  {
    Error_Handler();
  }
}

/* ============================== USART2 ============================== */
/**
  * @brief USART2 Initialization Function (CubeMX generated).
  * @details
  * Used as debug/log UART (115200 8N1).
  */
static void MX_USART2_UART_Init(void)
{
  huart2.Instance = USART2;                      /**< Peripheral instance selection. */
  huart2.Init.BaudRate = 115200;                 /**< Baud rate. */
  huart2.Init.WordLength = UART_WORDLENGTH_8B;   /**< 8-bit word length. */
  huart2.Init.StopBits = UART_STOPBITS_1;        /**< 1 stop bit. */
  huart2.Init.Parity = UART_PARITY_NONE;         /**< No parity. */
  huart2.Init.Mode = UART_MODE_TX_RX;            /**< Enable TX and RX. */
  huart2.Init.HwFlowCtl = UART_HWCONTROL_NONE;   /**< No flow control. */
  huart2.Init.OverSampling = UART_OVERSAMPLING_16; /**< Oversampling by 16. */
  if (HAL_UART_Init(&huart2) != HAL_OK)
  {
    Error_Handler();
  }
}

/* ============================== GPIO ============================== */
/**
  * @brief GPIO Initialization Function (CubeMX generated).
  * @details
  * Enables clocks for GPIO ports and configures PC13/PC14/PC15 as push-pull outputs.
  * LEDs are ACTIVE-HIGH, so RESET means OFF.
  */
static void MX_GPIO_Init(void)
{
  GPIO_InitTypeDef GPIO_InitStruct = {0}; /**< GPIO configuration structure. */

  __HAL_RCC_GPIOC_CLK_ENABLE(); /**< Enable clock for GPIOC. */
  __HAL_RCC_GPIOA_CLK_ENABLE(); /**< Enable clock for GPIOA. */
  __HAL_RCC_GPIOB_CLK_ENABLE(); /**< Enable clock for GPIOB. */

  /* Active-high LEDs: start OFF */
  HAL_GPIO_WritePin(GPIOC, GPIO_PIN_13|GPIO_PIN_14|GPIO_PIN_15, GPIO_PIN_RESET);

  GPIO_InitStruct.Pin = GPIO_PIN_13|GPIO_PIN_14|GPIO_PIN_15; /**< Select pins PC13, PC14, PC15. */
  GPIO_InitStruct.Mode = GPIO_MODE_OUTPUT_PP;                 /**< Push-pull output mode. */
  GPIO_InitStruct.Pull = GPIO_NOPULL;                         /**< No pull-up/pull-down. */
  GPIO_InitStruct.Speed = GPIO_SPEED_FREQ_LOW;                /**< Low speed (sufficient for LED). */
  HAL_GPIO_Init(GPIOC, &GPIO_InitStruct);                     /**< Apply configuration. */
}

/* ============================== Error Handler ============================== */
/**
  * @brief Error handler.
  * @details
  * Disables interrupts and loops forever. Used when a HAL init fails.
  */
void Error_Handler(void)
{
  __disable_irq();
  while (1)
  {
  }
}

#ifdef USE_FULL_ASSERT
/**
  * @brief  Reports the name of the source file and the source line number
  *         where the assert_param error has occurred.
  * @param  file Pointer to the source file name
  * @param  line assert_param error line source number
  * @details
  * Only compiled when USE_FULL_ASSERT is enabled.
  */
void assert_failed(uint8_t *file, uint32_t line)
{
  (void)file;
  (void)line;
}
#endif /* USE_FULL_ASSERT */
